#From  baselined alpine image
#Change the below from base image with NYL alpine image
FROM alpine as base 



#get dotnet sdk package for alpine
RUN apk add --no-cache dotnet6-sdk

# Enable only require .net core runtime
#RUN sudo apk add dotnet7-runtime

# Enable when .net core & asp.net core runtime
#The ASP.NET Core Runtime allows you to run apps that were made with .NET that didn't provide the runtime.
RUN apk add --no-cache aspnetcore6-runtime

RUN dotnet --help





